version: '3.1'

services:
  local-data-api:
    image: koxudaxi/local-data-api
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      RESOURCE_ARN: "${RDS_DATA_API_CLIENT_RESOURCE_ARN}"
      SECRET_ARN: "${RDS_DATA_API_CLIENT_SECRETARN}"
    ports:
      - "8080:80"
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: "${RDS_DATA_API_CLIENT_DATABASE}"
    ports:
      - "3306:3306"
